#!/usr/bin/env bash
#SBATCH --job-name=Flux_Monitor_SCEN_5
#SBATCH --partition=nodes
#SBATCH --time=2-00:00:00
#SBATCH --ntasks=20
#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --account=pet-hadron-2019
#SBATCH --mail-type=ALL
#SBATCH --mail-user=bp969@york.ac.uk
#SBATCH --output=%x-%j.log
#SBATCH --error=%x-%j.err

set -e

module purge

module load Geant4/11.2.2-GCC-12.3.0

cmake .

make

chmod +x run_batch.sh
./run_batch.sh